@startuml
package Equipment
{
    entity "Player"
    {
        //this is not Database
        ---
        EquipmentList [(装備id,所持数)]
    }
    entity "Equipment" 
    {
        +Id [装備のid]
        ---
        Eequipmenttype[装備の種類(Weapon,Head,UpperArmor,BottomArmor,Accessory)]
        -Id [種類ごとのid]
    }
    entity "Weapon"
    {
        +Id [種類ごとのid]
        ---
        Name [装備名]
        Stats [ステータス]
        Effect [装備効果]
    }
    entity "Head"
    {
        +Id [種類ごとのid]
        ---
        Name [装備名]
        Stats [ステータス]
        Effect [装備効果]
    }
    entity "UpperArmor"
    {
        +Id [種類ごとのid]
        ---
        Name [装備名]
        Stats [ステータス]
        Effect [装備効果]
    }
    entity "BottomArmor"
    {
        +Id [種類ごとのid]
        ---
        Name [装備名]
        Stats [ステータス]
        Effect[装備効果]
    }
    entity "Accessory"
    {
        +Id [種類ごとのid]
        ---
        Name [装備名]
        Stats [ステータス]
        Effect [装備効果]
    }
    entity "Equipment_Enhancement"
    {
        +Id [装備id]
        ---
        MaterialList [(アイテムid,必要数)]
        -EnhancedEquipmentid [強化先装備id]
    }
    Player --o{Equipment
    Equipment ||--o{ Weapon
    Equipment ||--o{ Head
    Equipment ||--o{ UpperArmor
    Equipment ||--o{ BottomArmor
    Equipment ||--o{ Accessory
    Equipment -left- Equipment_Enhancement

@enduml
